### ISSUE TITLE
Dockerfile error and suggested updates.

### ISSUE THREAD

**Issue by MurrayData** [joehoeller/Anaconda-CUDA-Accelerated-TensorFlowGPU-Development-Environment#3]
I amended the Dockerfile, and created a pull request for:

1. Base container amended to CUDA 10.1 from 10.0
2. Specified Python3 versions of libraries in installations as not always installed by default.
3. Added "-y" to TensorRT install 'apt-get install' commands as Docker build failed on unattended installation.

**Comment by daddydrac** [comment]
@MurrayData numbers 1 and 3 are taken care of, but I am not understanding number 2. It installs miniconda: python 3.7 by default. Can you please provide more detail?

**Comment by MurrayData** [comment]
It was my set up @joehoeller, now fixed.

**Comment by daddydrac** [comment]
@MurrayData  - Thanks for pointing out the other errors though. If you catch anything else please do let me know. Can I consider this issue closed then? (Please advise).
